import {ArrowRight,Check} from 'lucide-react'
import {useMemo,useState} from 'react'
import type {FormEvent} from 'react'
import type {Product} from '../types'

type CartItem={product:Product;qty:number;color?:string;size?:string}
type Props={items:CartItem[];onBack:()=>void;onComplete:(info:{name:string;phone:string;province:string;city:string;address:string;postalCode:string;notes:string})=>void}

const toman=(n:number)=>new Intl.NumberFormat('fa-IR').format(n)+' تومان'

export default function CheckoutPage({items,onBack,onComplete}:Props){
 const [form,setForm]=useState({name:'',phone:'',province:'',city:'',address:'',postalCode:'',notes:''})
 const [submitted,setSubmitted]=useState(false)
 const total=useMemo(()=>items.reduce((s,i)=>s+i.product.price*i.qty,0),[items])
 const update=(key:keyof typeof form,value:string)=>setForm(f=>({...f,[key]:value}))
 const submit=(e:FormEvent)=>{e.preventDefault();setSubmitted(true);onComplete(form)}
 if(items.length===0)return <main className="checkout-page"><div className="checkout-empty"><h1>سبد خرید خالی است</h1><p>برای ثبت سفارش ابتدا محصولی به سبد اضافه کنید.</p><button className="primary-btn" onClick={onBack}>بازگشت به فروشگاه</button></div></main>
 if(submitted)return <main className="checkout-page"><div className="checkout-success"><span className="success-icon"><Check/></span><span className="eyebrow">ORDER RECEIVED</span><h1>اطلاعات سفارش ثبت شد.</h1><p>در این نسخه، پرداخت آنلاین نداریم. سفارش شما با اطلاعات واردشده آماده بررسی است.</p><button className="primary-btn" onClick={onBack}>بازگشت به فروشگاه</button></div></main>
 return <main className="checkout-page container"><div className="checkout-head"><button className="back-link" onClick={onBack}><ArrowRight/> بازگشت به سبد</button><span className="eyebrow">ARKA / CHECKOUT</span><h1>اطلاعات سفارش</h1><p>مشخصات دریافت سفارش را وارد کنید.</p></div><div className="checkout-layout"><form className="checkout-form" onSubmit={submit}><section className="checkout-section"><h2>اطلاعات تماس</h2><div className="form-grid"><label>نام و نام خانوادگی<input required value={form.name} onChange={e=>update('name',e.target.value)} placeholder="مثلاً سینا مقصودی"/></label><label>شماره موبایل<input required type="tel" inputMode="tel" pattern="09[0-9]{9}" value={form.phone} onChange={e=>update('phone',e.target.value)} placeholder="۰۹۱۲۱۲۳۴۵۶۷"/></label></div></section><section className="checkout-section"><h2>آدرس تحویل</h2><div className="form-grid"><label>استان<input required value={form.province} onChange={e=>update('province',e.target.value)} placeholder="استان"/></label><label>شهر<input required value={form.city} onChange={e=>update('city',e.target.value)} placeholder="شهر"/></label></div><label>آدرس کامل<textarea required rows={4} value={form.address} onChange={e=>update('address',e.target.value)} placeholder="خیابان، کوچه، پلاک، واحد..."/></label><label>کد پستی<input required inputMode="numeric" pattern="[0-9۰-۹]{10}" value={form.postalCode} onChange={e=>update('postalCode',e.target.value)} placeholder="۱۰ رقم"/></label></section><section className="checkout-section"><h2>توضیحات سفارش <span>اختیاری</span></h2><textarea rows={3} value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="اگر نکته‌ای درباره سفارش یا تحویل دارید..."/></section><button className="primary-btn checkout-submit" type="submit">ثبت اطلاعات سفارش <ArrowRight/></button></form><aside className="checkout-summary"><span className="eyebrow">ORDER SUMMARY</span><h2>خلاصه سفارش</h2>{items.map(i=><div className="checkout-item" key={`${i.product.id}-${i.color??''}-${i.size??''}`}><img src={i.product.image} alt={i.product.alt}/><div><strong>{i.product.name}</strong><small>{i.qty} × {toman(i.product.price)}</small>{(i.size||i.color)&&<small>{i.size&&`سایز ${i.size}`}{i.size&&i.color?' · ':''}{i.color&&`رنگ ${i.color}`}</small>}</div></div>)}<div className="checkout-total"><span>جمع کل</span><strong>{toman(total)}</strong></div><p className="checkout-note">پرداخت در این مرحله انجام نمی‌شود؛ فقط اطلاعات سفارش ثبت می‌شود.</p></aside></div></main>
}